<a href="https://colab.research.google.com/github/Priyankakannan96/Priyanka-K/blob/main/Numpy_Assignment_Day_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <center> Numpy Basics </center>

In [ ]:
#import numpy module with alias np

import numpy as np

We can create a NumPy ndarray object by using the array() function.
To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:


In [ ]:
# Define a numpy array passing a list with  1,2 and 3 as elements in it
a1= np.array([1,2,3])



In [ ]:
# print output
print(a1)


[1 2 3]


## Dimensions in Arrays

Create arrays of different dimentions.

a=A numpy array with one single integer 10

b=A numpy array passing a list having a list= [1,2,3]

c=A numpy array passing nested list having [[1, 2, 3], [4, 5, 6]] as elements

d=A numpy array passing nested list having [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements

In [ ]:
#define a,b,c and d as instructed above

a = np.array(10)
b= np.array([1,2,3])
c= np.array ([[1, 2, 3], [4, 5, 6]])
d= np.array ([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])




Are you ready to check its dimention? Use ndim attribute on each variable to check its dimention

In [ ]:
#print dimentions of a,b, c and d
print(a,b,c,d)
print(np.ndim(a))
print(np.ndim(b))
print(np.ndim(c))
print(np.ndim(d))




10 [1 2 3] [[1 2 3]
 [4 5 6]] [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
0
1
2
3


Hey hey. Did you see! you have created 0-D,1-DeprecationWarning, 2-D and 3-D arrays.

Lets print there shape as well. You can check shape using shape attribute



In [ ]:
# print shape of each a,b ,c and d
print("\nShapes:")
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)






Shapes:
()
(3,)
(2, 3)
(2, 2, 3)


Lets check data type passed in our array. To check data type you can use dtype attribute

In [ ]:
# print data type of c and d
print(c.dtype)
print(d.dtype)




int64
int64


Above output mean our array is having int type elements in it.

Lets check the type of our variable. To check type of any numpy variable use type() function

In [ ]:
#print type of a and b variable
print(type(a))
print(type(b))





<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
# Lets check length of array b, using len() function
print(len(b))

3


Bravo!You have Defined ndarray i.e numpy array in variable a nd b. Also you have successfully learned how to create numpy.

Create two list l1 and l2 where, l1=[10,20,30] and l2=[40,50,60]
Also define two numpy arrays l3,l4 where l3 has l1 as element and l4 has l2 as element


In [3]:
# Define l1,l2,l3 and l4 as stated above.
import numpy as np

# Create lists
l1 = [10, 20, 30]
l2 = [40, 50, 60]

# Create NumPy arrays
l3 = np.array(l1)
l4 = np.array(l2)

print("List l1:", l1)
print("List l2:", l2)
print("NumPy array l3:", l3)
print("NumPy array l4:", l4)



List l1: [10, 20, 30]
List l2: [40, 50, 60]
NumPy array l3: [10 20 30]
NumPy array l4: [40 50 60]


Lets multiply each elements of l1 with corresponding elements of l2

Here use list comprehention to do so. Lets see how much you remember your work in other assignments.

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line<br>
eg. %timeit my_code

In [7]:
#code here as instructed above
result_list = [a * b for a, b in zip(l1, l2)]
print("Result using list comprehension:", result_list)

%timeit [a * b for a, b in zip(l1, l2)]


Result using list comprehension: [6, 14, 24, 36, 50]
967 ns ± 262 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Lets mulptiply l3 and l4

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line

In [12]:
import numpy as np


result_list = [a * b for a, b in zip(l3, l4)]
print("Result using list comprehension:", result_list)
# Measure time taken for element-wise multiplication
%timeit l3 * l4

Result using list comprehension: [400, 1000, 1800]
559 ns ± 9.15 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Don't worry if still your one line of code is running. Its because your system is calculating total time taken to run your code.

Did you notice buddy! time taken to multiply two lists takes more time than multiplyimg two numpy array.
Hence proved that numpy arrays are faster than lists.

**Fun Fact time!:**

You know in many data science interviews it is asked that what is the difference between list and array.<br>


In [13]:
#Create a numpy array using arange with 1 and 11 as parameter in it

import numpy as np

# Create a NumPy array with arange
array = np.arange(1, 11)
print("NumPy array:", array)


NumPy array: [ 1  2  3  4  5  6  7  8  9 10]


This means using arrange we get evenly spaced values within a given interval. Interval? Yes you can mention interval as well as third parameter in it.

In [14]:
# Create an array using arange passing 1,11 and 2 as parameter in iter
# Create a NumPy array with arange
array = np.arange(1, 11, 2)
print("NumPy array:", array)



NumPy array: [1 3 5 7 9]


In [15]:
# create numpy array using eye function with 3 as passed parameter

# Create a NumPy array using the eye function
array = np.eye(3)
print("NumPy array using eye:\n", array)


NumPy array using eye:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# Using arange() to generate numpy array x with numbers between 1 to 16
# x=
# Create a NumPy array x with numbers from 1 to 16
x = np.arange(1, 17)
print("NumPy array x:", x)


NumPy array x: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [17]:
# Reshape x with 2 rows and 8 columns

# Create the original array
x = np.arange(1, 17)

# Reshape x into 2 rows and 8 columns
reshaped_x = x.reshape(2, 8)
print("Reshaped array:\n", reshaped_x)


Reshaped array:
 [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


As you can see above that our x changed into 2D matrix

2. Reshaping 1-D to 3-D array


In [18]:
# reshaoe x with dimension that will have 2 arrays that contains 4 arrays, each with 2 elements:


# Create the original array
x = np.arange(1, 17)

# Reshape x into a shape (2, 4, 2)
reshaped_x = x.reshape(2, 4, 2)
print("Reshaped array:\n", reshaped_x)


Reshaped array:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [19]:
# Use unknown dimention to reshape x into 2-D numpy array with shape 4*4
# Create the original array
x = np.arange(1, 17)

# Reshape x into a 4x4 matrix
reshaped_x = x.reshape(4, 4)
print("Reshaped array:\n", reshaped_x)



Reshaped array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [20]:
# Use unknown dimention to  reshape x into 3-D numpy array with 2 arrays that contains 4 arrays
# y=

# Create the original array
y = np.arange(1, 17)

# Reshape x into a 3D array with shape (2, 4, 2)
reshaped_x = x.reshape(2, 4, 2)
print("Reshaped array:\n", reshaped_x)

# print y



Reshaped array:
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [21]:
# Flattening y

# Create a 3D array
y = np.arange(1, 17).reshape(2, 4, 2)

# Flatten the 3D array
flattened_y = y.flatten()  # or y.ravel()
print("Flattened array:", flattened_y)


Flattened array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [22]:
# Create an array a with all even numbers between 1 to 17
# a =

# Create an array with even numbers between 1 and 17
a = np.arange(2, 18, 2)
print("Array a:", a)

# print a


Array a: [ 2  4  6  8 10 12 14 16]


In [23]:
# Get third element in array a
# Create the array
a = np.arange(2, 18, 2)

# Get the third element
third_element = a[2]  # Index starts from 0
print("Third element:", third_element)

Third element: 6


In [24]:
#Print 3rd, 5th, and 7th element in array a
# Create the array
a = np.arange(2, 18, 2)

# Get the 3rd, 5th, and 7th elements
third_element = a[2]  # Index starts from 0
fifth_element = a[4]
seventh_element = a[6]

print("3rd element:", third_element)
print("5th element:", fifth_element)
print("7th element:", seventh_element)



3rd element: 6
5th element: 10
7th element: 14


Lets check the same for 2 D array

In [26]:
# Define an array 2-D a with [[1,2,3],[4,5,6],[7,8,9]] as its elements.
# a =

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("2D array a:\n", a)

2D array a:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
# print the 3rd element from the 3rd row of a
# Define the 2D array
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Get the 3rd element from the 3rd row (index 2)
third_element_third_row = a[2, 2]
print("3rd element from the 3rd row:", third_element_third_row)


3rd element from the 3rd row: 9


Well done!

Now lets check indexing for 3 D array

In [28]:
# Define an array b again with [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] as its elements.
# b =

b = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3D array b:\n", b)


3D array b:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [29]:
# Print 3rd element from 2nd list which is 1st list in nested list passed. Confusing right? 'a' have nested array.Understand the braket differences.
# Define the 3D array
b = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Get the 3rd element from the 2nd list (which is the 1st list in the nested structure)
third_element_second_list = b[1, 0, 2]
print("3rd element from the 2nd list (1st list in nested structure):", third_element_second_list)



3rd element from the 2nd list (1st list in nested structure): 9


In [30]:
# Create 1D array

# arr=
arr = np.array([10, 20, 30, 40, 50])
print("1D array:", arr)



1D array: [10 20 30 40 50]


In [31]:
# Slice elements from 1st to 5th element from the following array:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Slice elements from 1st to 5th element
sliced_arr = arr[0:5]
print("Sliced array (1st to 5th element):", sliced_arr)




Sliced array (1st to 5th element): [10 20 30 40 50]


Note: The result includes the start index, but excludes the end index.



In [32]:
# Slice elements from index 5 to the end of the array:

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Slice elements from index 5 to the end
sliced_arr = arr[5:]
print("Sliced array (from index 5 to end):", sliced_arr)


Sliced array (from index 5 to end): [60 70 80 90]


In [33]:
# Slice elements from the beginning to index 5 (not included):

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Slice elements from the beginning to index 5 (not included)
sliced_arr = arr[:5]
print("Sliced array (beginning to index 5):", sliced_arr)




Sliced array (beginning to index 5): [10 20 30 40 50]


**STEP**

Use the step value to determine the step of the slicing:

In [34]:
# Print every other element from index 1 to index 7:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Slice every other element from index 1 to 7
sliced_arr = arr[1:8:2]
print("Sliced array (every other element from index 1 to 7):", sliced_arr)



Sliced array (every other element from index 1 to 7): [20 40 60 80]


Did you see? using step you were able to get alternate elements within specified index numbers.

In [35]:
# Return every other element from the entire array arr:
# Create a 1D array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# Slice every other element
sliced_arr = arr[::2]
print("Every other element:", sliced_arr)



Every other element: [10 30 50 70 90]


well done!

Lets do some slicing on 2-D array also. We already have 'a' as our 2-D array. We will use it here.

**Array slicing in 2-D array.**

In [36]:
# Print array a
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Print the array
print("Array a:\n", a)




Array a:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
# From the third element, slice elements from index 1 to index 5 (not included) from array 'a'

# Create a 2D array
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# From the third element (2nd row), slice elements from index 1 to 5 (not included)
sliced_elements = a[2, 1:5]
print("Sliced elements (from index 1 to 5):", sliced_elements)


Sliced elements (from index 1 to 5): [8 9]


In [38]:
# In array 'a' print index 2 from all the elements :

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Print index 2 (third element) from all rows
index_2_elements = a[:, 2]
print("Index 2 (third element) from all rows:", index_2_elements)



Index 2 (third element) from all rows: [3 6 9]


In [39]:
# From all the elements in 'a', slice index 1 till end, this will return a 2-D array:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slice index 1 (second column) till the end
sliced_array = a[:, 1:]
print("Sliced array (from index 1 to end):\n", sliced_array)



Sliced array (from index 1 to end):
 [[2 3]
 [5 6]
 [8 9]]


Hurray! You have learned Slicing in Numpy array. Now you know to access any numpy array.

## Numpy copy vs view

In [42]:
import numpy as np

# Create a 1D array
x1 = np.array([1, 2, 3, 4, 5])
print("x1:", x1)

x1: [1 2 3 4 5]


In [ ]:
# assign x2 = x1



In [43]:
#print x1 and x2
# Create a 1D array x1
x1 = np.array([1, 2, 3, 4, 5])

# Assign x2 as a copy of x1
x2 = x1

print("x1:", x1)
print("x2:", x2)



x1: [1 2 3 4 5]
x2: [1 2 3 4 5]


Ok now you have seen that both of them are same

In [44]:
# change 1st element of x2 as 10

# Create a 1D array x1
x1 = np.array([1, 2, 3, 4, 5])

# Assign x2 as a copy of x1
x2 = x1

# Change the first element of x2
x2[0] = 10

print("x1:", x1)
print("x2:", x2)



x1: [10  2  3  4  5]
x2: [10  2  3  4  5]


In [45]:
#Again print x1 and x2
print(x1)
print(x2)



[10  2  3  4  5]
[10  2  3  4  5]


In [46]:
# Check memory share between x1 and x2

# Create a 1D array x1
x1 = np.array([1, 2, 3, 4, 5])

# Assign x2 as a copy of x1
x2 = x1

# Check if x2 has the same base (memory) as x1
print("x1 base:", x1.base)
print("x2 base:", x2.base)

x1 base: None
x2 base: None


Hey It's True they both share memory

Shall we try **view()** function also likwise.

In [47]:
# Create a view of x1 and store it in x3.
# x3 =
x1 = np.array([1, 2, 3, 4, 5])

# Create a view of x1 and store it in x3
x3 = x1.view()

# Check if x3 has the same base (memory) as x1
print("x1 base:", x1.base)
print("x3 base:", x3.base)

x1 base: None
x3 base: [1 2 3 4 5]


In [48]:
# Again check memory share between x1 and x3

x1 = np.array([1, 2, 3, 4, 5])

# Create a view of x1 and store it in x3
x3 = x1.view()

# Check if x3 has the same base (memory) as x1
print("x1 base:", x1.base)
print("x3 base:", x3.base)


x1 base: None
x3 base: [1 2 3 4 5]


Woh! simple assignment is similar to view. That means
The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

Don't agree? ok lets change x3 and see if original array i.e. x1 also changes

In [49]:
#Change 1st element of x3=100
x1 = np.array([1, 2, 3, 4, 5])

# Create a view of x1 and store it in x3
x3 = x1.view()

# Change the first element of x3
x3[0] = 100

print("x1:", x1)
print("x3:", x3)


x1: [100   2   3   4   5]
x3: [100   2   3   4   5]


In [50]:
#print x1 and x3 to check if changes reflected in both

x1 = np.array([1, 2, 3, 4, 5])

# Create a view of x1 and store it in x3
x3 = x1.view()

# Change the first element of x3
x3[0] = 100

# Print x1 and x3
print("x1:", x1)
print("x3:", x3)


x1: [100   2   3   4   5]
x3: [100   2   3   4   5]


Now its proved.

Lets see how **Copy()** function works

In [51]:
# Now create an array x4 which is copy of x1

# x4=
# Create a 1D array x1
x1 = np.array([1, 2, 3, 4, 5])

# Create a copy of x1 and store it in x4
x4 = x1.copy()

# Modify the first element of x4
x4[0] = 100

# Print x1 and x4
print("x1:", x1)
print("x4:", x4)


x1: [1 2 3 4 5]
x4: [100   2   3   4   5]


In [52]:
# Change the last element of x4 as 900
x1 = np.array([1, 2, 3, 4, 5])

# Create a copy of x1 and store it in x4
x4 = x1.copy()

# Change the last element of x4
x4[-1] = 900

# Print x1 and x4
print("x1:", x1)
print("x4:", x4)




x1: [1 2 3 4 5]
x4: [  1   2   3   4 900]


In [53]:
# print both x1 and x4 to check if changes reflected in both
x1 = np.array([1, 2, 3, 4, 5])

# Create a copy of x1 and store it in x4
x4 = x1.copy()

# Change the last element of x4
x4[-1] = 900

# Print x1 and x4
print("x1:", x1)
print("x4:", x4)




x1: [1 2 3 4 5]
x4: [  1   2   3   4 900]


Hey! such an intresting output. You noticed buddy! your original array didn't get changed on change of its copy ie. x4.

Still not convinced? Ok lets see if they both share memory or not

In [54]:
#Check memory share between x1 and x4

x1 = np.array([1, 2, 3, 4, 5])

# Create a copy of x1 and store it in x4
x4 = x1.copy()

# Check if x4 has the same base (memory) as x1
print("x1 base:", x1.base)
print("x4 base:", x4.base)



x1 base: None
x4 base: None


**hstack vs vstack function**


Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

NumPy provides a helper function:

1. hstack() to stack along rows.
2. vstack()  to stack along columns

In [55]:
# stack x1 and x4 along columns.
# Create a 1D array x1
x1 = np.array([1, 2, 3, 4, 5])

# Create a copy of x1 and store it in x4
x4 = x1.copy()

# Horizontal stacking (along columns)
horizontal_stack = np.hstack((x1.reshape(-1, 1), x4.reshape(-1, 1)))
print("Horizontal Stack:\n", horizontal_stack)

# Vertical stacking (along rows)
vertical_stack = np.vstack((x1, x4))
print("Vertical Stack:\n", vertical_stack)


Horizontal Stack:
 [[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]]
Vertical Stack:
 [[1 2 3 4 5]
 [1 2 3 4 5]]


In [56]:
#stack x1 and x4 along rows

x1 = np.array([1, 2, 3, 4, 5])

# Create a copy of x1 and store it in x4
x4 = x1.copy()

# Vertical stacking (along rows)
vertical_stack = np.vstack((x1, x4))
print("Vertical Stack:\n", vertical_stack)

Vertical Stack:
 [[1 2 3 4 5]
 [1 2 3 4 5]]


We hope now you saw the difference between them.

Fun fact! you can even use concatenate() function to join 2 arrays along with the axis. If axis is not explicitly passed, it is taken as 0 ie. along column

Lets try this function as well

In [57]:
# arr1 =


# arr2 =


##join arr1 and arr2 along rows using concatenate() function

# Create two 1D arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

# Join arr1 and arr2 along rows
concatenated = np.concatenate((arr1.reshape(-1, 1), arr2.reshape(-1, 1)), axis=0)
print("Concatenated along rows:\n", concatenated)



Concatenated along rows:
 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [58]:
##join arr1 and arr2 along columns using concatenate() function
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

# Join arr1 and arr2 along columns
concatenated = np.concatenate((arr1.reshape(1, -1), arr2.reshape(1, -1)), axis=0)
print("Concatenated along columns:\n", concatenated)


Concatenated along columns:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## Adding, Insert and delete Numpy array

You can also add 2 arrays using append() function also. This function appends values to end of array

Lets see how

In [59]:
# append arr2 to arr1

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

# Append arr2 to arr1
appended_array = np.append(arr1, arr2)
print("Appended Array:", appended_array)

Appended Array: [ 1  2  3  4  5  6  7  8  9 10]


Lets use insert() function which Inserts values into array before specified index value

In [60]:
# Inserts values into array x1 before index 4 with elements of x4

x1 = np.array([1, 2, 3, 4, 5])

# Create a copy of x1 and store it in x4
x4 = x1.copy()

# Change the last element of x4
x4[-1] = 900

# Insert values of x4 into x1 before index 4
x1 = np.insert(x1, 4, x4)

print("Modified x1:", x1)

Modified x1: [  1   2   3   4   1   2   3   4 900   5]


You can see in above output we have inserted all the elements of x4 before index 4 in array x1.

In [61]:
# delete 2nd element from array x2
x2 = np.array([1, 2, 3, 4, 5])

# Delete the 2nd element (index 1)
x2 = np.delete(x2, 1)

print("Modified x2:", x2)



Modified x2: [1 3 4 5]


Did you see? 2 value is deleted from x2 which was at index position 2

Good Job learner!